#!/usr/bin/env python3
"""Generate review assets and the native geometry header from the same SVG geometry."""
from pathlib import Path
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parent
INK = "#17191b"
RED = "#e54230"
WHITE = "#f4f5f5"

# Original: 154×138px. Ring center ≈(84.1,65.9), dot ≈(109.6,40.4).
# Normalize translation only: outer R=27.5, inner R=17.25, dot R=7.5;
# centers separated by (25.5,-25.5). Transparent artwork bounds are centered.
def mark(color):
    return f'''<circle cx="37.25" cy="42.75" r="22.375" fill="none" stroke="{color}" stroke-width="10.25"/>
<circle cx="62.75" cy="17.25" r="7.5" fill="{RED}"/>'''

def logo(color):
    return f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 80 80" role="img" aria-label="soRound OS 标志：圆环与红点">
{mark(color)}
</svg>'''

def about(english=False):
    title = "About" if english else "关于本机"
    return f'''<svg xmlns="http://www.w3.org/2000/svg" width="466" height="466" viewBox="0 0 466 466" role="img" aria-label="soRound OS {title}设计稿">
<circle cx="233" cy="233" r="233" fill="#000"/>
<circle cx="233" cy="233" r="225" fill="none" stroke="#101517" stroke-width="8"/>
<path d="M233 8 A225 225 0 1 1 8.44 247.13" fill="none" stroke="{WHITE}" stroke-width="8" stroke-linecap="round"/>
<g font-family="Helvetica Neue, Arial, PingFang SC, sans-serif" text-anchor="middle">
<circle cx="123" cy="74" r="22" fill="#181818"/>
<path d="M126 67 L119 74 L126 81" fill="none" stroke="{WHITE}" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/>
<text x="233" y="77" font-size="24" fill="{WHITE}">{title}</text>
<g transform="translate(163 105) scale(1.75)">{mark(WHITE)}</g>
<text x="233" y="279" font-size="34" font-weight="500" letter-spacing="-.6" fill="{WHITE}">soRound OS</text>
<text x="233" y="315" font-size="19" fill="#a1a4a6">v1.7-beta.27</text>
<path d="M180 342 H286" stroke="#24282a" stroke-width="1"/>
<text x="233" y="376" font-size="19" fill="#a1a4a6">ESP32-S3</text>
<text x="233" y="406" font-size="16" fill="#757b7e">466 × 466 AMOLED</text>
</g>
</svg>'''

def boot():
    return f'''<svg xmlns="http://www.w3.org/2000/svg" width="466" height="466" viewBox="0 0 466 466" role="img" aria-label="soRound OS 开机动画，1.8秒，单次播放">
<circle cx="233" cy="233" r="233" fill="#000"/>
<g transform="translate(153 153) scale(2)">
<circle cx="37.25" cy="42.75" r="22.375" fill="none" stroke="{WHITE}" stroke-width="10.25" stroke-linecap="round" pathLength="1" stroke-dasharray="1 1" stroke-dashoffset="1" transform="rotate(45 37.25 42.75)">
<animate attributeName="stroke-dashoffset" from="1" to="0" begin=".16s" dur=".74s" calcMode="spline" keyTimes="0;1" keySplines=".22 .61 .36 1" fill="freeze"/>
</circle>
<g transform="rotate(90 37.25 42.75)">
<animateTransform attributeName="transform" type="rotate" from="90 37.25 42.75" to="0 37.25 42.75" begin=".12s" dur=".88s" calcMode="spline" keyTimes="0;1" keySplines=".22 .61 .36 1" fill="freeze"/>
<circle cx="62.75" cy="17.25" r="7.5" fill="{RED}" opacity="0">
<animate attributeName="opacity" from="0" to="1" begin=".08s" dur=".16s" fill="freeze"/>
</circle>
</g>
</g>
<text x="233" y="342" text-anchor="middle" font-family="Helvetica Neue, Arial, sans-serif" font-size="26" font-weight="500" fill="{WHITE}" opacity="0">
soRound OS
<animate attributeName="opacity" from="0" to="1" begin="1.02s" dur=".28s" fill="freeze"/>
<animate attributeName="y" from="349" to="342" begin="1.02s" dur=".28s" calcMode="spline" keyTimes="0;1" keySplines=".22 .61 .36 1" fill="freeze"/>
</text>
</svg>'''

def main():
    assets = {"logo.svg": logo(INK), "logo-dark.svg": logo(WHITE),
              "about.svg": about(), "about-en.svg": about(True), "boot.svg": boot()}
    for name, contents in assets.items():
        (ROOT / name).write_text(contents + "\n", encoding="utf-8")
    # The firmware geometry is derived from the approved vector, not traced from a raster.
    vector = ET.fromstring(assets["logo-dark.svg"])
    ring, dot = vector
    geometry = {"VIEWBOX": vector.attrib["viewBox"].split()[2],
                "RING_CX": ring.attrib["cx"], "RING_CY": ring.attrib["cy"],
                "OUTER_RADIUS": float(ring.attrib["r"]) + float(ring.attrib["stroke-width"]) / 2,
                "STROKE": ring.attrib["stroke-width"], "DOT_CX": dot.attrib["cx"],
                "DOT_CY": dot.attrib["cy"], "DOT_RADIUS": dot.attrib["r"]}
    header = "#pragma once\n// Generated by artwork/identity/generate.py from logo-dark.svg.\n"
    header += "".join(f"#define IDENTITY_{key} {float(value)}f\n" for key, value in geometry.items())
    header += f"#define IDENTITY_WHITE 0x{WHITE[1:]}\n#define IDENTITY_RED 0x{RED[1:]}\n"
    (ROOT.parent.parent / "main" / "identity_geometry.h").write_text(header, encoding="utf-8")
    template = (ROOT / "preview.template.html").read_text(encoding="utf-8")
    for key, value in {"{{LOGO}}": assets["logo.svg"], "{{LOGO_DARK}}": assets["logo-dark.svg"],
                       "{{ABOUT}}": assets["about.svg"], "{{ABOUT_EN}}": assets["about-en.svg"],
                       "{{BOOT}}": assets["boot.svg"]}.items():
        template = template.replace(key, value)
    (ROOT / "index.html").write_text(template, encoding="utf-8")
    print("Generated 5 SVG assets, the self-contained review page and native geometry header.")

if __name__ == "__main__":
    main()
