// Run from GeekTool-IDF: swift tools/gen_answer_font.swift
// Local CoreText, original answer/UI literals only; no shared-font replacement.
import Foundation
import CoreText
import CoreGraphics

var codes = Set<UInt32>(32...126)
// Public responses may use standard Western and Chinese punctuation beyond the bundled phrases.
codes.formUnion([0x00a0,0x00b7,0x2013,0x2014,0x2018,0x2019,0x201c,0x201d,0x2026,
                 0x3000,0x3001,0x3002,0xff01,0xff0c,0xff1a,0xff1b,0xff1f])
let pattern = try NSRegularExpression(pattern:#""(?:\\.|[^"\\])*""#)
for source in ["main/app_answers.c", "main/answer_messages.h"] {
    let text = try String(contentsOfFile:source,encoding:.utf8)
    for match in pattern.matches(in:text,range:NSRange(text.startIndex..<text.endIndex,in:text)) {
        for scalar in text[Range(match.range,in:text)!].unicodeScalars where scalar.value > 126 {
            codes.insert(scalar.value)
        }
    }
}
let size=32, height=40, baseline=7
let ordered=codes.sorted()
var bitmap:[UInt8]=[], chunks:[String]=[], glyphs=["{0,0,0,0,0,0}"]
for code in ordered {
    let font=CTFontCreateWithName(((0x4e00...0x9fff).contains(code) ? "PingFangSC-Regular":"HelveticaNeue") as CFString,CGFloat(size),nil)
    let attrs=[kCTFontAttributeName:font,kCTForegroundColorAttributeName:CGColor(gray:1,alpha:1)] as CFDictionary
    let line=CTLineCreateWithAttributedString(CFAttributedStringCreate(nil,String(UnicodeScalar(code)!) as CFString,attrs))
    let advance=CTLineGetTypographicBounds(line,nil,nil,nil), width=max(2,Int(ceil(advance))+4)
    let ctx=CGContext(data:nil,width:width,height:height,bitsPerComponent:8,bytesPerRow:width,
                      space:CGColorSpaceCreateDeviceGray(),bitmapInfo:CGImageAlphaInfo.none.rawValue)!
    ctx.setAllowsAntialiasing(true);ctx.setShouldSmoothFonts(false)
    ctx.textPosition=CGPoint(x:2,y:baseline);CTLineDraw(line,ctx)
    let pixels=ctx.data!.bindMemory(to:UInt8.self,capacity:width*height)
    var x0=width,y0=height,x1=0,y1=0
    for y in 0..<height {for x in 0..<width where pixels[y*width+x]>>4 != 0 {
        x0=min(x0,x);y0=min(y0,y);x1=max(x1,x+1);y1=max(y1,y+1)
    }}
    let w=max(0,x1-x0),h=max(0,y1-y0),offset=bitmap.count
    var values:[UInt8]=[]
    if w>0 && h>0 {for y in y0..<y1 {for x in x0..<x1 {values.append(pixels[y*width+x]>>4)}}}
    var bytes:[UInt8]=[]
    for i in stride(from:0,to:values.count,by:2) {
        bytes.append(values[i]<<4 | (i+1<values.count ? values[i+1]:0))
    }
    bitmap += bytes
    chunks.append(String(format:"/* U+%04X */",code)+"\n"+bytes.enumerated().map {i,v in
        String(format:"0x%02x,",v)+(i%24==23 ? "\n":"")
    }.joined()+"\n")
    glyphs.append("{.bitmap_index=\(offset),.adv_w=\(Int((advance*16).rounded())),.box_w=\(w),.box_h=\(h),.ofs_x=\(w>0 ? x0-2:0),.ofs_y=\(h>0 ? height-y1-baseline:0)}")
}
let first=ordered[0],last=ordered.last!
let output="""
// Generated by tools/gen_answer_font.swift; original answer-book subset, 32px, cropped 4bpp.
#include "lvgl.h"
LV_FONT_DECLARE(font_answer_cjk_32);
static const uint8_t bitmap[]={
\(chunks.joined())};
static const lv_font_fmt_txt_glyph_dsc_t glyphs[]={
\(glyphs.joined(separator:",\n"))};
static const uint16_t unicode[]={\(ordered.map{String($0-first)}.joined(separator:","))};
static const lv_font_fmt_txt_cmap_t cmaps[]={{.range_start=\(first),.range_length=\(last-first+1),.glyph_id_start=1,.unicode_list=unicode,.list_length=\(ordered.count),.type=LV_FONT_FMT_TXT_CMAP_SPARSE_TINY}};
static const lv_font_fmt_txt_dsc_t dsc={.glyph_bitmap=bitmap,.glyph_dsc=glyphs,.cmaps=cmaps,.cmap_num=1,.bpp=4};
const lv_font_t font_answer_32={.get_glyph_dsc=lv_font_get_glyph_dsc_fmt_txt,.get_glyph_bitmap=lv_font_get_bitmap_fmt_txt,.line_height=\(height),.base_line=\(baseline),.dsc=&dsc,.fallback=&font_answer_cjk_32};
"""
try output.write(toFile:"main/font_answer.c",atomically:true,encoding:.utf8)
print("answer font: \(ordered.count) glyphs, \(bitmap.count) bitmap bytes")
