// Authored paths in the reviewed prototype are the source of truth; emit fixed native maps.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'..'),context=vm.createContext({});
vm.runInContext(fs.readFileSync(path.join(root,'artwork/analog-play/levels.js'),'utf8'),context);
const levels=vm.runInContext('levels',context);
const en=['First turn','Switchback','Corridor','Four turns','Serpentine','Zigzag','Crossing','Spiral','Long hall','Narrow gate','Offset','Homeward'];
let source='// Generated by tools/gen_maze_levels.cjs from artwork/analog-play/levels.js.\n#include "maze_levels.h"\nconst maze_level_t maze_levels[MAZE_LEVEL_COUNT]={\n';
for(const [i,level] of levels.entries())source+=`    {${level.n},${level.path.length-1},${JSON.stringify(level.name)},${JSON.stringify(en[i])},{${level.walls.join(',')}}},\n`;
fs.writeFileSync(path.join(root,'main/maze_levels.c'),source+'};\n');
console.log('Generated 12 fixed native maze layouts.');
