#!/usr/bin/env python3
"""Embed the three baseline 466px JPEGs so OTA also supplies the defaults."""
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
source=['// Generated by tools/gen_watchface_backgrounds.py.\n#include "watchface_backgrounds.h"\n']
for name in ('type','orbit','shift'):
    data=(ROOT/f'artwork/watchfaces/{name}.jpg').read_bytes()
    source.append(f'static const uint8_t jpeg_{name}[]={{\n'+
                  '\n'.join(','.join(f'0x{b:02x}' for b in data[i:i+24])+',' for i in range(0,len(data),24))+'\n};\n')
source.append('const watchface_jpeg_t watchface_backgrounds[3]={'+
              ','.join('{jpeg_'+n+',sizeof jpeg_'+n+'}' for n in ('type','orbit','shift'))+'};\n')
(ROOT/'main/watchface_backgrounds.c').write_text(''.join(source))
