// cd GeekTool-IDF && swift tools/gen_weather_details_fonts.swift
// Only new detail-page CJK glyphs and middle dot; existing first-screen fonts and artwork stay byte-identical.
import Foundation
import CoreText
import CoreGraphics
let source=try String(contentsOfFile:"main/weather_details.c",encoding:.utf8)
let literals=try NSRegularExpression(pattern:#""(?:\\.|[^"\\])*""#)
var codes=Set<UInt32>()
for match in literals.matches(in:source,range:NSRange(source.startIndex..<source.endIndex,in:source)) {
    for c in source[Range(match.range,in:source)!].unicodeScalars where (0x4e00...0x9fff).contains(c.value) || c.value==0x00b7 {codes.insert(c.value)}
}
var output="// Generated by tools/gen_weather_details_fonts.swift; detail-only glyph subsets, 2bpp.\n#include \"weather_ui.h\"\n"
for size in [16,20] {
    let ordered=codes.sorted(),height=size+6,baseline=5
    var bitmap:[UInt8]=[],glyphs=["{0,0,0,0,0,0}"]
    for code in ordered {
        let font=CTFontCreateWithName("PingFangSC-Regular" as CFString,CGFloat(size),nil)
        let attrs=[kCTFontAttributeName:font,kCTForegroundColorAttributeName:CGColor(gray:1,alpha:1)] as CFDictionary
        let line=CTLineCreateWithAttributedString(CFAttributedStringCreate(nil,String(UnicodeScalar(code)!) as CFString,attrs))
        let advance=CTLineGetTypographicBounds(line,nil,nil,nil),width=Int(ceil(advance))+4
        let ctx=CGContext(data:nil,width:width,height:height,bitsPerComponent:8,bytesPerRow:width,space:CGColorSpaceCreateDeviceGray(),bitmapInfo:CGImageAlphaInfo.none.rawValue)!
        ctx.setAllowsAntialiasing(true);ctx.setShouldSmoothFonts(false);ctx.textPosition=CGPoint(x:2,y:baseline);CTLineDraw(line,ctx)
        let pixels=ctx.data!.bindMemory(to:UInt8.self,capacity:width*height)
        var x0=width,y0=height,x1=0,y1=0
        for y in 0..<height {for x in 0..<width where pixels[y*width+x]>=43 {x0=min(x0,x);y0=min(y0,y);x1=max(x1,x+1);y1=max(y1,y+1)}}
        let w=max(0,x1-x0),h=max(0,y1-y0),offset=bitmap.count
        var values:[UInt8]=[]
        if w>0 && h>0 {for y in y0..<y1 {for x in x0..<x1 {values.append(UInt8((Int(pixels[y*width+x])*3+127)/255))}}}
        for i in stride(from:0,to:values.count,by:4) {var b:UInt8=0;for k in 0..<4 where i+k<values.count {b |= values[i+k] << (6-2*k)};bitmap.append(b)}
        glyphs.append("{.bitmap_index=\(offset),.adv_w=\(Int((advance*16).rounded())),.box_w=\(w),.box_h=\(h),.ofs_x=\(x0-2),.ofs_y=\(height-y1-baseline)}")
    }
    let first=ordered[0],last=ordered.last!
    output += """
    static const uint8_t bitmap_\(size)[]={\(bitmap.enumerated().map {i,v in String(format:"0x%02x,",v)+(i%24==23 ? "\n":"")}.joined())};
    static const lv_font_fmt_txt_glyph_dsc_t glyphs_\(size)[]={\(glyphs.joined(separator:",\n"))};
    static const uint16_t unicode_\(size)[]={\(ordered.map {String($0-first)}.joined(separator:","))};
    static const lv_font_fmt_txt_cmap_t cmaps_\(size)[]={{.range_start=\(first),.range_length=\(last-first+1),.glyph_id_start=1,.unicode_list=unicode_\(size),.list_length=\(ordered.count),.type=LV_FONT_FMT_TXT_CMAP_SPARSE_TINY}};
    static const lv_font_fmt_txt_dsc_t dsc_\(size)={.glyph_bitmap=bitmap_\(size),.glyph_dsc=glyphs_\(size),.cmaps=cmaps_\(size),.cmap_num=1,.bpp=2};
    const lv_font_t font_wx_detail_\(size)={.get_glyph_dsc=lv_font_get_glyph_dsc_fmt_txt,.get_glyph_bitmap=lv_font_get_bitmap_fmt_txt,.line_height=\(height),.base_line=\(baseline),.dsc=&dsc_\(size),.fallback=&font_weather_\(size)};

    """
    print("detail \(size)px: \(ordered.count) glyphs, \(bitmap.count) bytes")
}
try output.write(toFile:"main/font_weather_details.c",atomically:true,encoding:.utf8)
