#!/usr/bin/env python3
"""Rasterize pinned Barlow subsets; preserve 4bpp pixels with LVGL lossless RLE."""
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont
import json
import subprocess

ROOT = Path(__file__).resolve().parents[1]
FONTS = ROOT / "artwork/watchfaces/fonts"
OUTPUT = ROOT / "main/font_watchface.c"
SUBSETS = [(s, "regular", ''.join(chr(c) for c in range(32, 127)) + '°')
           for s in (7, 9, 14, 18)]
SUBSETS += [(s, "black", "0123456789:-°") for s in (26, 36, 52, 56, 72, 82, 104, 112, 164)]
SUBSETS = [(size,weight,subset,f'font_wf_{size}') for size,weight,subset in SUBSETS]
# Approved clocks use separate weights: light ring digits, medium horizontal
# clocks/temperatures, and oversized black stacked digits. Export only needed pairs.
SUBSETS += [(size,weight,"0123456789:-°",f'font_wf_{weight}_{size}')
            for weight,sizes in (('regular',(48,96)),('black',(94,188)),
                                 ('semibold',(14,26,28,52,56,104,112))) for size in sizes]

def generate(subsets=SUBSETS, output=OUTPUT):
    source = ['// Generated by tools/gen_watchface_fonts.py; lossless 4bpp Barlow subsets.\n'
              '// Copyright 2017 The Barlow Project Authors; SIL OFL 1.1.\n'
              '// License and pinned source: artwork/watchfaces/fonts/.\n#include "watchface_ui.h"\n'
              'LV_FONT_DECLARE(font_cn16);\n'
              'static const char font_license[]='+json.dumps((FONTS/'OFL.txt').read_text())+';\n']
    for size, weight, subset, symbol in subsets:
        filename={'regular':'Regular','black':'Black','semibold':'SemiBold'}[weight]
        font = ImageFont.truetype(str(FONTS / f"Barlow-{filename}.ttf"), size)
        codes = sorted(set(map(ord, subset)))
        boxes = [font.getbbox(chr(code), anchor="ls") for code in codes]
        top = min(b[1] for b in boxes); bottom = max(b[3] for b in boxes)
        bitmap = []; records = []; filtered_glyphs = []; raw_glyphs = []
        for code, (x0, y0, x1, y1) in zip(codes, boxes):
            width, height = x1-x0, y1-y0
            image = Image.new('L', (max(1,width), max(1,height)))
            ImageDraw.Draw(image).text((-x0, -y0), chr(code), font=font, fill=255, anchor="ls")
            # Crop true ink bounds; advance remains the original proportional font metric.
            bounds = image.getbbox()
            if bounds:
                ink = image.crop(bounds); width, height = ink.size
                x = x0 + bounds[0]; y = -(y0 + bounds[3])
                values = [p >> 4 for p in ink.tobytes()]
                raw_glyphs.append([(values[i] << 4) | (values[i+1] if i+1<len(values) else 0)
                                   for i in range(0,len(values),2)])
                # LVGL's built-in XOR prefilter preserves every original 4bpp value.
                filtered_glyphs.append([value ^ (values[i-width] if i >= width else 0)
                                        for i,value in enumerate(values)])
            else:
                width=height=x=y=0
                filtered_glyphs.append([])
                raw_glyphs.append([])
            records.append((round(font.getlength(chr(code))*16),width,height,x,y))
        encoded = json.loads(subprocess.run(
            ['node', str(ROOT/'tools/compress_watchface_fonts.js')],
            input=json.dumps(filtered_glyphs), text=True, capture_output=True, check=True).stdout)
        raw_bytes = sum(map(len,raw_glyphs))
        compressed = sum(map(len,encoded)) < raw_bytes
        payloads = encoded if compressed else raw_glyphs
        glyphs = ['{0,0,0,0,0,0}']
        for record,payload in zip(records,payloads,strict=True):
            glyphs.append('{.bitmap_index=%d,.adv_w=%d,.box_w=%d,.box_h=%d,.ofs_x=%d,.ofs_y=%d}' %
                          (len(bitmap),*record))
            bitmap.extend(payload)
        key = f'{weight}_{size}'
        source.append(f'static const uint8_t bitmap_{key}[]={{\n' +
                      '\n'.join(','.join(f'0x{p:02x}' for p in bitmap[i:i+24])+',' for i in range(0,len(bitmap),24)) + '\n};\n')
        source.append(f'static const lv_font_fmt_txt_glyph_dsc_t glyphs_{key}[]={{'+',\n'.join(glyphs)+'};\n')
        source.append(f'static const uint16_t unicode_{key}[]={{'+','.join(str(c-codes[0]) for c in codes)+'};\n')
        source.append(f'static const lv_font_fmt_txt_cmap_t cmap_{key}[]={{'
                      f'{{.range_start={codes[0]},.range_length={codes[-1]-codes[0]+1},.glyph_id_start=1,'
                      f'.unicode_list=unicode_{key},.list_length={len(codes)},.type=LV_FONT_FMT_TXT_CMAP_SPARSE_TINY}}}};\n')
        source.append(f'static const lv_font_fmt_txt_dsc_t dsc_{key}={{.glyph_bitmap=bitmap_{key},'
                      f'.glyph_dsc=glyphs_{key},.cmaps=cmap_{key},.cmap_num=1,.bpp=4,'
                      f'.bitmap_format={"LV_FONT_FMT_TXT_COMPRESSED" if compressed else "LV_FONT_FMT_TXT_PLAIN"}}};\n')
        fallback=',.fallback=&font_cn16' if weight=='regular' else ''
        source.append(f'const lv_font_t {symbol}={{.get_glyph_dsc=lv_font_get_glyph_dsc_fmt_txt,'
                      f'.get_glyph_bitmap=lv_font_get_bitmap_fmt_txt,.line_height={bottom-top},'
                      f'.base_line={bottom},.dsc=&dsc_{key}{fallback},.user_data=(void *)font_license}};\n')
        print(f'{weight} {size}px: {len(codes)} glyphs, {raw_bytes} -> {len(bitmap)} bytes (lossless)')
    output.write_text(''.join(source))

if __name__ == '__main__':
    import argparse
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--hands', action='store_true', help='Only generate the small analog numeral subsets')
    args = parser.parse_args()
    if args.hands:
        generate([(size, weight, '0123456789', f'font_hand_{weight}_{size}')
                  for weight, sizes in [('regular', (12,24)), ('semibold', (16,32))] for size in sizes],
                 ROOT / 'main/font_watchface_hands.c')
    else:
        generate()
