#!/usr/bin/env python3
"""Convert the preserved wooden-fish source into a baseline JPEG for the existing decoder."""
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
ART = ROOT / "artwork/merit"
image = Image.open(ART / "source.png").convert("RGB")
assert image.size == (1536, 1024), "Keep the source composition at its original 3:2 aspect ratio"
image.resize((288, 192), Image.Resampling.LANCZOS).save(
    ART / "wooden-fish.jpg", quality=95, subsampling=0, progressive=False)
data = (ART / "wooden-fish.jpg").read_bytes()
assert len(data) < 50000, "Keep this artwork inside the existing OTA slot budget"
source = ['// Generated by tools/gen_merit_artwork.py; preserved source in artwork/merit.\n',
          '#include "merit_artwork.h"\nconst uint8_t merit_jpeg[]={\n']
source += [','.join(f'0x{b:02x}' for b in data[i:i+24])+',\n' for i in range(0, len(data), 24)]
source.append('};\nconst size_t merit_jpeg_size=sizeof merit_jpeg;\n')
(ROOT / "main/merit_artwork.c").write_text(''.join(source))
print(f"wooden fish: 288x192 baseline JPEG, {len(data)} bytes")
