// Run from GeekTool-IDF: swift tools/gen_coin_font.swift
// Four face marks only; local CoreText, no external assets or shared-font changes.
import Foundation
import CoreText
import CoreGraphics

let size = 52, height = 62, baseline = 8
let codes = "HT正反".unicodeScalars.map { $0.value }.sorted()
var bitmap: [UInt8] = [], glyphs = ["{0,0,0,0,0,0}"]
for code in codes {
    let font = CTFontCreateUIFontForLanguage(.system, CGFloat(size), nil)!
    let attributes = [kCTFontAttributeName: font, kCTForegroundColorAttributeName: CGColor(gray: 1, alpha: 1)] as CFDictionary
    let line = CTLineCreateWithAttributedString(CFAttributedStringCreate(nil, String(UnicodeScalar(code)!) as CFString, attributes))
    let advance = CTLineGetTypographicBounds(line, nil, nil, nil)
    let width = max(4, Int(ceil(advance)) + 4)
    let context = CGContext(data: nil, width: width, height: height, bitsPerComponent: 8, bytesPerRow: width,
                            space: CGColorSpaceCreateDeviceGray(), bitmapInfo: CGImageAlphaInfo.none.rawValue)!
    context.setAllowsAntialiasing(true); context.setShouldSmoothFonts(false)
    context.textPosition = CGPoint(x: 2, y: baseline); CTLineDraw(line, context)
    let pixels = context.data!.bindMemory(to: UInt8.self, capacity: width * height)
    var x0 = width, y0 = height, x1 = 0, y1 = 0
    for y in 0..<height { for x in 0..<width where pixels[y * width + x] >= 9 {
        x0 = min(x0, x); y0 = min(y0, y); x1 = max(x1, x + 1); y1 = max(y1, y + 1)
    } }
    let w = max(0, x1 - x0), h = max(0, y1 - y0), offset = bitmap.count
    var values: [UInt8] = []
    if w > 0 && h > 0 { for y in y0..<y1 { for x in x0..<x1 { values.append(pixels[y * width + x] >> 4) } } }
    for i in stride(from: 0, to: values.count, by: 2) {
        bitmap.append(values[i] << 4 | (i + 1 < values.count ? values[i + 1] : 0))
    }
    glyphs.append("{.bitmap_index=\(offset),.adv_w=\(Int((advance * 16).rounded())),.box_w=\(w),.box_h=\(h),.ofs_x=\(x0 - 2),.ofs_y=\(height - y1 - baseline)}")
}
let first = codes[0], last = codes.last!
let output = """
// Generated by tools/gen_coin_font.swift; four 52px face marks, cropped 4bpp.
#include "lvgl.h"
static const uint8_t bitmap[]={
\(bitmap.enumerated().map { i,v in String(format: "0x%02x,", v) + (i % 24 == 23 ? "\n" : "") }.joined())};
static const lv_font_fmt_txt_glyph_dsc_t glyphs[]={\(glyphs.joined(separator: ",\n"))};
static const uint16_t unicode[]={\(codes.map { String($0 - first) }.joined(separator: ","))};
static const lv_font_fmt_txt_cmap_t cmaps[]={{.range_start=\(first),.range_length=\(last - first + 1),.glyph_id_start=1,.unicode_list=unicode,.list_length=\(codes.count),.type=LV_FONT_FMT_TXT_CMAP_SPARSE_TINY}};
static const lv_font_fmt_txt_dsc_t dsc={.glyph_bitmap=bitmap,.glyph_dsc=glyphs,.cmaps=cmaps,.cmap_num=1,.bpp=4};
const lv_font_t font_coin_52={.get_glyph_dsc=lv_font_get_glyph_dsc_fmt_txt,.get_glyph_bitmap=lv_font_get_bitmap_fmt_txt,.line_height=\(height),.base_line=\(baseline),.dsc=&dsc};

"""
try output.write(toFile: "main/font_coin.c", atomically: true, encoding: .utf8)
print("coin: \(codes.count) glyphs, \(bitmap.count) bitmap bytes")
