// Native CoreText -> tightly cropped 2bpp antialiased glyphs for new location UI.
// This font adds coverage; existing weather 4bpp fonts remain untouched.
import Foundation
import CoreText
import CoreGraphics
let text = try String(contentsOfFile:"artwork/locations/names.txt",encoding:.utf8)
var codes = Set<UInt32>(32...126)
// Page-string scans can shrink after copy changes. Retain every shipped glyph,
// including historical labels, before adding the current pages' characters.
let previous = try String(contentsOfFile:"main/font_location_24.c",encoding:.utf8)
let historical=try NSRegularExpression(pattern:#"U\+([0-9A-Fa-f]{4,6})"#)
for match in historical.matches(in:previous,range:NSRange(previous.startIndex..<previous.endIndex,in:previous)) {
    if let range=Range(match.range(at:1),in:previous),let code=UInt32(previous[range],radix:16) {codes.insert(code)}
}
for c in (text+"省市区选择地址常用最近其他地点确认保存失败亮度音量常显静音表盘语言关于开启关闭拖动调整上下滑动切换点击试听中文").unicodeScalars where c.value>126 { if c.value != 10 { codes.insert(c.value) } }
let literals=try NSRegularExpression(pattern:#""(?:\\.|[^"\\])*""#)
for source in ["main/weather_location_ui.c","main/app_settings.c","main/app_wifi.c","main/app_answers.c","main/app_zodiac.c","main/zodiac_data.c","main/app_merit.c","main/i18n.c"] {
    let content=try String(contentsOfFile:source,encoding:.utf8)
    for match in literals.matches(in:content,range:NSRange(content.startIndex..<content.endIndex,in:content)) {
        for c in content[Range(match.range,in:content)!].unicodeScalars where c.value>126 {codes.insert(c.value)}
    }
}
let size=24, height=32, baseline=6
var bitmap:[UInt8]=[], glyphs=["{0,0,0,0,0,0}"], chunks:[String]=[]
let ordered=codes.sorted()
for code in ordered {
    let str=String(UnicodeScalar(code)!)
    let font=CTFontCreateWithName(((0x4e00...0x9fff).contains(code) ? "PingFangSC-Regular":"HelveticaNeue") as CFString,CGFloat(size),nil)
    let attrs=[kCTFontAttributeName:font,kCTForegroundColorAttributeName:CGColor(gray:1,alpha:1)] as CFDictionary
    let line=CTLineCreateWithAttributedString(CFAttributedStringCreate(nil,str as CFString,attrs))
    let advance=CTLineGetTypographicBounds(line,nil,nil,nil), width=max(2,Int(ceil(advance))+4)
    let ctx=CGContext(data:nil,width:width,height:height,bitsPerComponent:8,bytesPerRow:width,space:CGColorSpaceCreateDeviceGray(),bitmapInfo:CGImageAlphaInfo.none.rawValue)!
    ctx.setAllowsAntialiasing(true);ctx.setShouldSmoothFonts(false);ctx.textPosition=CGPoint(x:2,y:baseline);CTLineDraw(line,ctx)
    let pixels=ctx.data!.bindMemory(to:UInt8.self,capacity:width*height)
    var x0=width,y0=height,x1=0,y1=0
    for y in 0..<height {for x in 0..<width where pixels[y*width+x]>=43 {x0=min(x0,x);y0=min(y0,y);x1=max(x1,x+1);y1=max(y1,y+1)}}
    let w=max(0,x1-x0),h=max(0,y1-y0),offset=bitmap.count
    var values:[UInt8]=[]
    if w>0 && h>0 {for y in y0..<y1 {for x in x0..<x1 {values.append(UInt8((Int(pixels[y*width+x])*3+127)/255))}}}
    var bytes:[UInt8]=[]
    for i in stride(from:0,to:values.count,by:4) {var b:UInt8=0;for j in 0..<4 where i+j<values.count {b |= values[i+j] << (6-2*j)};bytes.append(b)}
    bitmap += bytes
    chunks.append("/* U+"+String(code,radix:16)+" */\n"+bytes.enumerated().map {i,v in String(format:"0x%02x,",v)+(i%24==23 ? "\n":"")}.joined()+"\n")
    glyphs.append("{.bitmap_index=\(offset),.adv_w=\(Int((advance*16).rounded())),.box_w=\(w),.box_h=\(h),.ofs_x=\(w>0 ? x0-2:0),.ofs_y=\(h>0 ? height-y1-baseline:0)}")
}
let first=ordered[0],last=ordered.last!
let out="""
// Generated by tools/gen_location_font.swift; new location/settings font, 24px, 2bpp.
#include "lvgl.h"
static const uint8_t bitmap[]={
\(chunks.joined())};
static const lv_font_fmt_txt_glyph_dsc_t glyphs[]={
\(glyphs.joined(separator:",\n"))};
static const uint16_t unicode[]={\(ordered.map{String($0-first)}.joined(separator:","))};
static const lv_font_fmt_txt_cmap_t cmaps[]={{.range_start=\(first),.range_length=\(last-first+1),.glyph_id_start=1,.unicode_list=unicode,.list_length=\(ordered.count),.type=LV_FONT_FMT_TXT_CMAP_SPARSE_TINY}};
static const lv_font_fmt_txt_dsc_t dsc={.glyph_bitmap=bitmap,.glyph_dsc=glyphs,.cmaps=cmaps,.cmap_num=1,.bpp=2};
const lv_font_t font_location_24={.get_glyph_dsc=lv_font_get_glyph_dsc_fmt_txt,.get_glyph_bitmap=lv_font_get_bitmap_fmt_txt,.line_height=30,.base_line=6,.dsc=&dsc};
"""
try out.write(toFile:"main/font_location_24.c",atomically:true,encoding:.utf8)
print("location font: \(ordered.count) glyphs, \(bitmap.count) bitmap bytes")
