#pragma once
// Generated by artwork/identity/generate.py from logo-dark.svg.
#define IDENTITY_VIEWBOX 80.0f
#define IDENTITY_RING_CX 37.25f
#define IDENTITY_RING_CY 42.75f
#define IDENTITY_OUTER_RADIUS 27.5f
#define IDENTITY_STROKE 10.25f
#define IDENTITY_DOT_CX 62.75f
#define IDENTITY_DOT_CY 17.25f
#define IDENTITY_DOT_RADIUS 7.5f
#define IDENTITY_WHITE 0xf4f5f5
#define IDENTITY_RED 0xe54230
